# ~/.config/alacritty/alacritty.toml
# live_config_reload = false

[general]
# import = ["~/.config/alacritty/themes/themes/papercolor_dark.toml"]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark"]

[font]
size = 10.5
normal = { family = "Moralerspace Krypton", style = "Regular" }
bold   = { family = "Moralerspace Krypton", style = "Bold" }
italic = { family = "Moralerspace Krypton", style = "Italic" }
bold_italic = { family = "Moralerspace Krypton", style = "Bold Italic" }


[window]
dynamic_title = true
opacity = 0.80

[window.padding]
x = 0
y = 0

[selection]
save_to_clipboard = true

[mouse]
bindings = [
{ mouse = "Left", mods = "Control", action = "Paste" },
{ mouse = "Right", mods = "Control", action = "Copy" },
]

